#!/bin/bash
#PBS -l nodes=1:ppn=16
#PBS -l walltime=07:00:00:00

module load R

echo hostname
cd /oasis/scratch/hongqin/temp_project/mactower-network-failure-simulation/1.ori.ginppi.2015Oct
pwd

for p in 1.0 0.98 0.95 0.94 0.93 0.92 0.9 0.89 0.88 0.87 0.86 0.85 0.82 0.8 
do
   for LOne in 0.002 0.0021 0.0022 0.0023 0.0024 0.0025 0.0026 0.0028 0.0028 0.0029 0.003 0.0035 0.004 0.0045
   do
      echo "$p $LOne"
 Rscript netwk_aging_sim.v0.1b.R -if1 merged_PPIGIN_Factorized2015Oct132Cols.csv -if2 essentialGeneLookupTable_20151013.csv -l1 $LOne -l2 0 -dt 4 -p $p -n 5000 -op ginppi -od ginppi.ori.out -iC 16 -d 1 -h /oasis/scratch/hongqin/temp_project/mactower-network-failure-simulation/1.ori.ginppi.2015Oct
   done
done

